### ISSUE TITLE
nltk tagger is broken

### ISSUE THREAD

**Issue by brendano** [slanglab/phrasemachine#1]
i think for when the text is multiple sentences?  also why is it doing that regex tokenizer now?

```
>>> len(pm.get_stdeng_nltk_tagger().tag_text(text)['tokens'])
21
>>> len(pm.get_stdeng_nltk_tagger().tag_text(text)['pos'])
58
```

**Comment by brendano** [comment]
i think it's broken for all cases with multiple sentences.  current behavior:

```
>>> import phrasemachine.phrasemachine as pm
>>> text = "Hi I like this. OK another sentence."
>>> x=pm.get_stdeng_nltk_tagger().tag_text(text); (len(x['tokens']), len(x['pos']))
(3, 7)
```

it was working at this version.  correct behavior is to return parallel arrays for tokens and pos tags

```
~/posphrases/phrasemachine/py % git checkout 000d8b9
>>> import phrasemachine.phrasemachine as pm
>>> reload(pm)
>>> x=pm.get_stdeng_nltk_tagger().tag_text(text); (len(x['tokens']), len(x['pos']))
(63, 63)
```

**Comment by AbeHandler** [comment]
"also why is it doing that regex tokenizer now?" 

I changed it to a regex tagger when removing nltk download dependencies. changed back now to "treebank tagger", which is what it was doing before. 

(boring details: nltk.word_tokenize() calls treebank tokenizer, which is apparently just regexes, which is I think how they tokenize for PTB. https://github.com/nltk/nltk/blob/develop/nltk/tokenize/treebank.py#25).
