### ISSUE TITLE
learn regex

### ISSUE THREAD

**Issue by jwijffels** [slanglab/phrasemachine#12]
Hello, I just had a look to this R package, which looks pretty interesting.
If I understand this correctly by looking at the source code it basically does POS tagging and a sequence of tags is matched based on some kind of "regular expression" of tags like in "(A|N)*N(PD*(A|N)*N)*".
Can you also tell me if there exists tools that you know of which learn patterns like this sequence "(A|N)*N(PD*(A|N)*N)*" from an already POS tagged corpus.
I'm particularly interested for the purpose of poetry writing where I have a POS tagged corpus of an existing writer and would like to automate the writing methodology.

**Comment by AbeHandler** [comment]
Hi @jwijffels your understanding of what the software does is correct. I am not aware of packages that "learn" such regexes. I guess it would depend on what you mean by 'learn'. What kind of regex are you hoping to find with a learning method? I am going to close this issue but shoot me an email at abram DOT handler at gmail if you have more questions.
