### ISSUE TITLE
delete one of these dirs?

### ISSUE THREAD

**Issue by brendano** [slanglab/phrasemachine#3]
https://github.com/slanglab/phrasemachine/tree/master/phrasemachine/data

versus

https://github.com/slanglab/phrasemachine/tree/master/py/phrasemachine/data

**Comment by AbeHandler** [comment]
ah. i thought you wanted it for mysterious pip reasons. deleted the dir, pushed and pip still works.

**Comment by brendano** [comment]
oh awesome ( iwas confused abt pip)
